version: "3.9"

services:
  currywurst_service:
    restart: always
    build:
      context: ./currywurst_service
      dockerfile: ApiDockerfile
    ports:
      - "3003:3003"
    environment:
      - RABBITMQ_USERNAME=rabbit
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=dataqueue
      - RABBITMQ_EXCHANGE=exchange_test
      - DB_PATH=/code/storage_service/db/logs.txt
    networks:
        - rabbitmq_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=password
    networks:
        - rabbitmq_net

  storage_service:
    restart: always
    build: 
      context: ./storage_service
      dockerfile: StorageDockerfile
    volumes:
      - ./storage_service/db:/code/storage_service/db
    environment:
      - RABBITMQ_USERNAME=rabbit
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=dataqueue
      - RABBITMQ_EXCHANGE=exchange_test
      - DB_PATH=/code/storage_service/db/logs.txt
    networks:
        - rabbitmq_net
networks:
  rabbitmq_net:
    driver: bridge
